name: 🚀 Deploy & Quality Assurance 

on: 
  push: 
    branches:
      - main 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  deploy:
  name: 🚀 Deploy to Github pages
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'
  outputs:
    pages_url: ${{steps.deployment.outputs.page_url }}

environment:
   name: github-pages
   url: ${{steps.deployment.outputs.pages_url}}

steps:
- name: 📥 Checkout code
  uses: actions/checkout

- name: 📄 Setup Pages  
  uses: actions/configure-pages@v4

- name: 📦 upload artifact 
  uses: actions/upload-pages-artifact@v3




